export const routes = {
  procurement: '/procurement',
  audit: '/audit',
  productionPlans: '/production-plans',
  warehouse: '/warehouse',
  stockRevision: '/warehouse/revision',
  operations: '/operations',
  operationInstructionPattern: '/operations/:operationId/instruction',
  operationInstruction: (operationId: string) =>
    `/operations/${operationId}/instruction`,
  publicInstructionPattern: '/public/instructions/:token',
  processes: '/processes',
  processPrompt: '/processes/prompt',
  processEditorPattern: '/processes/:processId',
  processEditor: (processId: string) => `/processes/${processId}`,
  personnel: '/personnel',
  sales: '/sales',
  finance: '/finance',
  analytics: '/analytics',
} as const;
